layout : single

# Build settings
remote_theme: mmistakes/minimal-mistakes
environment: production
minimal_mistakes_skin : dark
search		      : false
encoding	: "utf-8"
locale: "fr-FR"

# Definitions du site
title	 	   : "Quentin Mareau"
title_separator          : "-"
description	   : "Ce site regroupe l'ensemble de mes ressources pédagogiques entre autres choses"
url	     	   : http://mareauq.github.io
logo		   : /_pages/images/ico.png
name : "Quentin Mareau"
location : "Paris" 
contact		   : quentin.mareaupro@gmail.com

author:
  name: "Quentin Mareau"
  avatar           : "/others/profile.png"
  bio              : "Enseignement et cryptographie"
  location         : "Paris, France"
  links:
    - label: "Email"
      icon: "fas fa-envelope-square"
      url: "mailto:quentin.mareaupro@gmail.com"

atom_feed:
  hide: true
  
include:
  - _pages

plugins:
  - jekyll-include-cache

analytics:
  provider: "google"
  google:
    tracking_id: "GTM-NZLGBQ4G"
    anonymize_ip: false
